services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps/api:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://db:27017/lms
      - JWT_SECRET=hasdjhasdhjasgdjhasgdjh
      - JWT_EXPIRES_IN=1d
      - MONGO
    networks:
      - lms

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    command: npm run dev
    networks:
      - lms

  db:
    image: mongo:latest
    container_name: lms-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - lms

volumes:
  mongo_data:


networks:
  lms:
    driver: bridge
